src/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#post views
	url(r'^$', views.post_list, name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
	#url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$', 
		views.post_detail, 
		name='post_detail'),

	url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),


]

src/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home_views.home, name='home'),
    url(r'^about/$', home_views.about, name='about'),

    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager

from markdown_deux import markdown

from django.utils.safestring import mark_safe

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

def upload_location(objects, filename):
	# filebase, extension = filename.split(".")
	# return "%s/%s.%s" %(instance.id, instance.id, extension)
	return "%s/%s" %(objects.id, filename)


class Post(models.Model):
	STATUS_CHOICES = (
			('draft', 'Draft'),
			('published', 'Published'),

		)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, related_name='blog_posts')
	body = models.TextField()
	image = models.ImageField(upload_to=upload_location,
			null=True,
			blank=True, 
			width_field= "width_field",
			height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	objects = models.Manager()#the default Manager
	published = PublishedManager() # Our custom manager
	tags = TaggableManager()


	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail',
					args=[self.publish.year,
						self.publish.strftime('%m'),
						self.publish.strftime('%d'),
						self.slug])

	def get_markdown(self):
		body = self.body
		markdown_text = markdown(body)
		return mark_safe(markdown_text)



class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)


	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)

src/home/models.py
from django.db import models

# Create your models here.

src/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta :
		model =Comment
		fields = ('name', 'email', 'body')

src/blog/views.py
from django.shortcuts import render, get_object_or_404

# pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView

# Create your views here.
from .models import Post, Comment

from .forms import EmailPostForm, CommentForm

from django.core.mail import send_mail

# Taggit view
from taggit.models import Tag

from django.db.models import Count

from django.db.models import Q





# list view
def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None
	


	query = request.GET.get("q")
	if query:
		object_list = object_list.filter(
				Q(title__icontains = query) |
				Q(body__icontains = query) |
				Q(author__first_name__icontains = query) |
				Q(author__last_name__icontains = query)				
				).distinct()


	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])


	paginator = Paginator(object_list, 7) # 3 post in each page 
	
	
	
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# if page is not an integer deliver the first page
		posts = paginator.page(1)
	except EmptyPage:
		# if page is not of range deliver last_page of results
		posts = paginator.page(paginator.num_pages)
	return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


#view all post
# class PostListView(ListView):
# 	queryset = Post.published.all()
# 	context_object_name = 'posts'
# 	paginate_by = 3
# 	template_name = 'blog/post/list.html'




#view post detail
def post_detail(request, year, month, day, post) :
	post  = get_object_or_404(Post, slug=post, 
									status='published',
									publish__year= year,
									publish__month= month,
									publish__day= day)
	# list of active comments for this post
	comments = post.comments.filter(active=True)

	if request.method == 'POST':
	# A comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Created Comment object but don't save to database yet

			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.post = post
			# Save the comment to the database
			new_comment.save()
	else:
		comment_form = CommentForm()

	# List similar posts
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

	return render(request, 
				'blog/post/detail.html', {'post': post, 'comments':comments, 'comment_form': comment_form, 'similar_posts': similar_posts})


# Email forms from forms.py

def post_share(request, post_id):
	# Retrieve post by id
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False

	if request.method == 'POST':
		# Form was submited
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Form fields passed validation
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reeading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'alifulmudzakir@gmail.com', [cd['to']])
			sent = True
			# . . . send email
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})
		

src/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
	
	template = 'home.html'
	return render(request, template)

def about(request):
	
	template = 'about.html'
	return render(request, template)

src/blog/templates/blog/blog.html
{% load blog_tags %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="icon" href="{% static 'img/zifza.ico' %}">

    <title> {% block title %}  {% endblock %} </title>

    <!-- Bootstrap core CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link rel='stylesheet' type='text/css' href='{% static "css/main.css" %}'>
  </head>

  <body>

    {% include 'navbarblog.html' %}

    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">{% block header_title %}  {% endblock %}</h1>
        <!-- <p class="lead blog-description">An example blog </p> -->
      </div>
    </div>

    <div class="container">

      <ol class="breadcrumb">
        <li>
          <a href='{% url "blog:post_list" %}'>Blog</a>
          {% block post_detail_link %}

          {% endblock %}
        </li>
        
      </ol>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            {% block content %}

		      	{% endblock %}
          </div><!-- /.blog-post -->


          

        </div><!-- /.blog-main -->

        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>My Blog</h4>
            <p>This is my blog. I've eritten {% total_posts %} posts so far. </p>
          </div>

           <div class="sidebar-module">
            <h4>Latest Post</h4>
            <ol class="list-unstyled">
            <p>
              {% show_latest_posts 5 %}
            </p>                   
            </ol>
          </div>

        
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
 

<!--  <script type="text/javascript">
  $(document).ready(function(){
    $(".content-markdown").each(function(){
         var content = $(this).text()
         var markedContent = marked(content)
         $(this).html(markedContent)
      })
    $(".markdown_text img").each(function(){
          $(this).addClass("img-responsive")
      
      })
   })
   


 </script> -->
  
  </body>
</html>

src/blog/templates/blog/post/detail.html
{% extends "blog/blog.html" %}


{% block title %} {{ post.title }} {% endblock %}

{% block header_title %} {{ post.title }}  {% endblock %}

{% block post_detail_link %}
/ <a href="{{ post.get_absolute_url }}">
 	{{ post.title }}
 </a>    
{% endblock %}


{% block content %}


<p class="date">
	Published {{ post.publish }} by {{ post.author }}
</p>

	<!-- {% if post.image %}
	<img src="{{ post.image.url }}" class="img-responsive">
	{% endif %} -->






{{ post.get_markdown }}
	

	<!-- <p>
		<a href="{% url "blog:post_share" post.id %}">Share This Post</a>
	</p> -->

	<h2>Similar posts</h2>
	{% for post in similar_posts %}
		<p>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</p>
	{% empty %}
		There are no similar posts yet.
	{% endfor %}


{% if new_comment %}
	<h2>your comment has ben added</h2>

{% else %}

	<h2>Add a new Comment</h2>
	<form action="." method="post">
		{{ comment_form.as_p }}
		{% csrf_token %}
		<p><input type="submit" value="add comment"></p>
	</form>
{% endif %}




{% with comments.count as total_comments %}
	<h2>
		{{ total_comments }} comment {{ total_comments|pluralize }}
	</h2>
{% endwith %}







{% for comment in comments %}
	<div class="comment">
		<p class="info">
			Comment {{ forloop.counter }} by {{ comment.name }}
		</p>
		{{ comment.body|linebreaks }}
	</div>
{% empty %}
	<p>There are no comment yet</p>

{% endfor %}


{% endblock %}

src/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_post %}
		<li>
			<a href="{{ post.get_absolute_url }}">
			{{ post.title }}</a>
		</li>

	{% endfor %}
</ul>

src/blog/templates/blog/post/list.html
{% extends "blog/blog.html" %}

{% block title %} my blog {% endblock %}


{% block header_title %} my blog  {% endblock %}

{% block content %}

{% if tag %}
		<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}
	<hr>

{% for post in posts %}
	
	
	<h2>
		<a href="{{ post.get_absolute_url }} ">{{ post.title}} </a>
	</h2>

	

 	<p class="tags">
 		Tags:
 		{% for tag in post.tags.all %}
 			<a href="{% url "blog:post_list_by_tag" tag.slug %}"> 
 			{{ tag.name }}
 			</a>
 			{% if not forloop.last %}, {% endif %}
 		{% endfor %}
 	</p>



	<p class="date">
		Published {{ post.publish }} by {{ post.author }}
	</p>

	{% if post.image %}
	<img src="{{ post.image.url }}" class="img-responsive">
	{% endif %}

	<hr>

	
	<!-- {{ post.get_markdown|truncatewords_html:30 }} -->
	
{% endfor %}


{% include "pagination.html" with page=posts %}

{% endblock %}

src/blog/templates/blog/post/share.html
{% extends "base.html" %}


{% block title %}Share a post{% endblock %}


{% block content %}
	{% if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
			"{{ post.title }}" was successfully sent to {{ cd.to }}.
		</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail</h1>

		<form action="." method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
		</form>
	{% endif %}

{% endblock %}

src/blog/templates/navbarblog.html
{% load staticfiles %}


<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a href="{% url 'home' %}"><img src="{% static 'img/zifza.png' %}" class='navbar-brand'/></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% url 'home' as home %}
      {% url 'about' as about %}
      
      <li {% if request.path == home %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li {% if request.path == about %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>

      <li {% if request.path == blog %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="/blog">Blog</a>
      </li>
     
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" value="{{ request.GET.q }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

src/blog/templates/pagination.html
<nav class="blog-pagination">
			<span class="step-links">
			{% if page.has_previous %}
            <a class="btn btn-outline-primary" href="?page={{ page.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Back</a>
            {% endif %}
           

            <span class="current"> Page {{ page.number}} of {{ page.paginator.num_pages }} </span>


            {% if page.has_next %}
            <a class="btn btn-outline-success" href="?page={{ page.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
            {% endif %}
            </span>
          </nav>

src/home/templates/about.html
{% extends 'base.html' %}


{% block content %}
	<h1>about page</h1>

{% endblock %}

src/home/templates/base.html
{% load blog_tags %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/zifza.ico' %}">

    <title> {% block title %}  {% endblock %} </title>

    <!-- Bootstrap core CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link rel='stylesheet' type='text/css' href='{% static "css/main.css" %}'>
  </head>

  <body>

    {% include 'navbar.html' %}

    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">{% block header_title %}  {% endblock %}</h1>
        <!-- <p class="lead blog-description">An example blog </p> -->
      </div>
    </div>

    <div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            {% block content %}

		      	{% endblock %}
          </div><!-- /.blog-post -->


          

        </div><!-- /.blog-main -->

        

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
 
  </body>
</html>

src/home/templates/home.html
{% extends 'base.html' %}


{% block content %}
	<h1>Home page</h1>

{% endblock %}

src/home/templates/navbar.html
{% load staticfiles %}


<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a href="{% url 'home' %}"><img src="{% static 'img/zifza.png' %}" class='navbar-brand'/></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% url 'home' as home %}
      {% url 'about' as about %}
      
      <li {% if request.path == home %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li {% if request.path == about %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>

      <li {% if request.path == blog %} class="nav-item active" {% endif %}>
        <a class="nav-link" href="/blog">Blog</a>
      </li>
     
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" value="{{ request.GET.q }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>